apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: golfapp
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/atidyshirt/golfapp-platform
              revision: main
              directories:
                - path: deploy/*
          - clusters: {}
  template:
    metadata:
      name: 'golfapp-{{path.basename}}'
    spec:
      project: golf-application
      source:
        repoURL: https://github.com/atidyshirt/golfapp-platform
        targetRevision: main
        path: '{{path}}'
        kustomize:
          commonAnnotations:
            addons_domain: '{{metadata.annotations.addons_domain}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: golf
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
