apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: dex
    repo: https://charts.dexidp.io
    version: 0.24.1
    releaseName: dex
    namespace: dex
    valuesFile: values.yaml

resources:
  - onepassword-items.yaml

replacements:
  - source:
      kind: Deployment
      name: dex
      fieldPath: spec.template.metadata.annotations.addons_domain
    targets:
      - select:
          kind: HTTPRoute
          name: dex
        fieldPaths:
          - spec.hostnames.0
        options:
          delimiter: '.'
          index: 1
