apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: oidc-auth0
  namespace: dex
spec:
  itemPath: "vaults/homelab/items/oidc.auth0"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: oidc-dex
  namespace: dex
spec:
  itemPath: "vaults/homelab/items/oidc.dex"
