apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ghcr-push
  namespace: argo-workflows
spec:
  itemPath: "vaults/homelab/items/ghcr-push"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gitops-bot
  namespace: argo-workflows
spec:
  itemPath: "vaults/homelab/items/gitops-bot"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: arc-github-token
  namespace: argo-workflows
spec:
  itemPath: "vaults/homelab/items/arc-github-token"
