apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/atidyshirt/home-server.git
        revision: main
        directories:
          - path: applications/*/base
  template:
    metadata:
      name: '{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/atidyshirt/home-server.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
