apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-onepassword-operator
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - {}
  template:
    metadata:
      name: onepassword-operator
    spec:
      project: default
      source:
        repoURL: https://github.com/atidyshirt/home-server.git
        targetRevision: main
        path: addons/onepassword-operator/base
      destination:
        server: https://kubernetes.default.svc
        namespace: onepassword
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
