apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-dex
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: dex
    spec:
      project: platform
      info:
        - name: Documentation
          value: https://dexidp.io/docs/
        - name: Source Code
          value: https://github.com/dexidp/dex
      source:
        repoURL: '{{metadata.annotations.addons_repo_url}}'
        targetRevision: '{{metadata.annotations.addons_repo_revision}}'
        path: applications/dex/base
        kustomize:
          commonAnnotations:
            addons_domain: '{{metadata.annotations.addons_domain}}'
            addons_node_ip: '{{metadata.annotations.addons_node_ip}}'
            addons_node_ip_v6: '{{metadata.annotations.addons_node_ip_v6}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dex
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
