apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-coredns-lan
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            coredns-lan.stack.enabled: "true"
  template:
    metadata:
      name: coredns-lan
    spec:
      project: platform
      info:
        - name: Documentation
          value: https://coredns.io/manual/toc/
        - name: Source Code
          value: https://github.com/atidyshirt/home-server/tree/main/applications/coredns-lan
      source:
        repoURL: '{{metadata.annotations.addons_repo_url}}'
        targetRevision: '{{metadata.annotations.addons_repo_revision}}'
        path: applications/coredns-lan/base
        kustomize:
          commonAnnotations:
            addons_domain: '{{metadata.annotations.addons_domain}}'
            addons_node_ip: '{{metadata.annotations.addons_node_ip}}'
            addons_node_ip_v6: '{{metadata.annotations.addons_node_ip_v6}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: coredns-lan
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
