apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: golfapp
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: golfapp
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
    spec:
      project: golf-application
      info:
        - name: Web
          value: 'golf.{{metadata.annotations.addons_domain}}'
        - name: Canary
          value: 'golf-canary.{{metadata.annotations.addons_domain}}'
        - name: Deployment
          value: https://github.com/atidyshirt/golfapp-platform
        - name: Source Code
          value: https://github.com/atidyshirt/golf-ai-experiment
      source:
        repoURL: https://github.com/atidyshirt/golfapp-platform
        targetRevision: main
        path: deploy
        kustomize:
          commonAnnotations:
            addons_domain: '{{metadata.annotations.addons_domain}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: golf
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
