apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-onepassword-operator
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: onepassword-operator
    spec:
      project: platform
      source:
        repoURL: '{{metadata.annotations.addons_repo_url}}'
        targetRevision: '{{metadata.annotations.addons_repo_revision}}'
        path: applications/onepassword-operator/base
        kustomize:
          commonAnnotations:
            addons_domain: '{{metadata.annotations.addons_domain}}'
            addons_node_ip: '{{metadata.annotations.addons_node_ip}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: onepassword
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
