apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-dex
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: dex
    spec:
      project: default
      source:
        repoURL: '{{metadata.annotations.addons_repo_url}}'
        targetRevision: '{{metadata.annotations.addons_repo_revision}}'
        path: applications/dex/base
        kustomize:
          commonAnnotations:
            addons_domain: '{{metadata.annotations.addons_domain}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dex
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
