apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: golfapp
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: golfapp
    spec:
      project: golf-application
      sources:
        - repoURL: https://github.com/atidyshirt/golfapp-platform
          targetRevision: main
          path: deploy
          kustomize:
            commonAnnotations:
              addons_domain: '{{metadata.annotations.addons_domain}}'
        - repoURL: https://github.com/atidyshirt/home-server.git
          targetRevision: main
          path: applications/ghcr-pull-secret/base
      destination:
        server: https://kubernetes.default.svc
        namespace: golf
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
