apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-lan-corefile
  namespace: coredns-lan
data:
  Corefile.tmpl: |
    PLACEHOLDER_DOMAIN:53 {
        file /etc/coredns/zones/PLACEHOLDER_DOMAIN.zone
        log
        errors
    }
    .:53 {
        forward . 1.1.1.1 1.0.0.1
        cache 30
        log
        errors
    }
