apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-lan-zones
  namespace: coredns-lan
data:
  zone.tmpl: |
    $ORIGIN PLACEHOLDER_DOMAIN.
    $TTL 3600
    @   IN  SOA ns.PLACEHOLDER_DOMAIN. admin.PLACEHOLDER_DOMAIN. (
            2026081800 ; serial
            7200       ; refresh
            3600       ; retry
            1209600    ; expire
            3600 )     ; minimum
    @       IN  NS  ns.PLACEHOLDER_DOMAIN.
    ns      IN  A   PLACEHOLDER_NODE_IP
    *       IN  A   PLACEHOLDER_NODE_IP
