apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    version: 2.4.1
    releaseName: onepassword-connect
    namespace: onepassword
    valuesInline:
      operator:
        create: true
        authMethod: connect
        autoRestart: true
        pollingInterval: 1800
      acceptanceTests:
        healthCheck:
          enabled: false
