apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argo-events
    repo: https://argoproj.github.io/argo-helm
    version: 2.4.24
    releaseName: argo-events
    namespace: argo-events

resources:
  - eventbus.yaml
  - httproute.yaml
  - pipeline/eventsource.yaml
  - pipeline/sensor.yaml

replacements:
  - source:
      kind: HTTPRoute
      name: build-trigger
      fieldPath: metadata.annotations.addons_domain
    targets:
      - select:
          kind: HTTPRoute
          name: build-trigger
        fieldPaths:
          - spec.hostnames.0
        options:
          delimiter: '.'
          index: 1
