apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 41.2.0
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - certificate.yaml

replacements:
  - source:
      kind: Certificate
      name: homelab-dev-tls
      fieldPath: metadata.annotations.addons_domain
    targets:
      - select:
          kind: Certificate
          name: homelab-dev-tls
        fieldPaths:
          - spec.dnsNames.0
      - select:
          kind: Certificate
          name: homelab-dev-tls
        fieldPaths:
          - spec.dnsNames.1
        options:
          delimiter: '.'
          index: 1
