apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-restricted
rules:
  - apiGroups: ['']
    resources: [pods, configmaps, services, secrets, persistentvolumeclaims]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ['']
    resources: [pods/log]
    verbs: [get]
  - apiGroups: [apps]
    resources: [statefulsets, daemonsets, deployments]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [argoproj.io]
    resources: [rollouts]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [gateway.networking.k8s.io]
    resources: [httproutes]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [onepassword.com]
    resources: [onepassworditems]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-restricted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-restricted
subjects:
  - kind: ServiceAccount
    name: default
